/**
 * Organizer seed themes + meaning-oriented concept maps for CLara Preliminary Synthesis.
 * Primary frame = this rubric (not auto-clustering).
 */

export const THEMES = [
  {
    id: "ai-principles-humanist",
    title: "AI Principles & The Humanist Stance",
    shortTitle: "AI Principles",
    concepts: [
      "ai principles",
      "humanist",
      "human meaning",
      "dignity",
      "human development",
      "capability expander",
      "efficiency",
      "speed vs depth",
      "speed versus depth",
      "safety vs experimentation",
      "safety versus experimentation",
      "polarity",
      "polarities",
      "human-centered",
      "human centred",
      "values",
      "ethical",
      "ethics",
      "flourishing",
      "agency",
      "augmentation",
      "not replacement",
      "human in the loop",
      "meaning-making",
      "meaning making",
    ],
  },
  {
    id: "organizational-overwhelm",
    title: 'Organizational Overwhelm & "Ludicrousness"',
    shortTitle: "Overwhelm",
    concepts: [
      "overwhelm",
      "overwhelmed",
      "confusion",
      "ludicrous",
      "ludicrousness",
      "job title",
      "ai mandated",
      "mandate",
      "mandated",
      "without definition",
      "clear definition",
      "breaks trust",
      "trust between",
      "leaders and employees",
      "shoved into",
      "ai washing",
      "hype",
      "chaos",
      "change fatigue",
      "initiative fatigue",
      "unclear progress",
      "definition of progress",
      "adoption pressure",
      "top-down",
      "top down",
    ],
  },
  {
    id: "expertise-paradox",
    title: "The Expertise Paradox",
    shortTitle: "Expertise Paradox",
    concepts: [
      "expertise paradox",
      "expertise",
      "evaluate ai",
      "catch errors",
      "entry-level",
      "entry level",
      "junior",
      "l&d",
      "learning and development",
      "learning & development",
      "cutting roles",
      "cutting entry",
      "build expertise",
      "craft",
      "apprenticeship",
      "domain knowledge",
      "quality control",
      "verify",
      "verification",
      "hallucination",
      "error catching",
      "skills gap",
      "capability building",
      "deskilling",
    ],
  },
  {
    id: "workplace-grief",
    title: "Workplace Grief",
    shortTitle: "Workplace Grief",
    concepts: [
      "grief",
      "grieving",
      "ambiguous grief",
      "disenfranchised grief",
      "loss of role",
      "disappearing",
      "ways of working",
      "death-doula",
      "death doula",
      "close out",
      "closing out",
      "mourning",
      "letting go",
      "identity",
      "familiar roles",
      "macro-level",
      "loss",
      "goodbye",
      "sunset",
      "wind down",
      "closure",
      "ritual",
    ],
  },
  {
    id: "workslop-economy",
    title: 'The "Workslop" Economy & Discernment',
    shortTitle: "Workslop & Discernment",
    concepts: [
      "workslop",
      "slop",
      "ai-generated",
      "ai generated",
      "low-effort",
      "low effort",
      "high-volume",
      "high volume",
      "cognitive load",
      "discernment tax",
      "discernment",
      "judgment",
      "judgement",
      "wisdom",
      "decision-making",
      "decision making",
      "middle layers",
      "middle management",
      "quality of content",
      "noise",
      "signal",
      "flood of",
      "content flood",
      "human judgment",
      "human judgement",
    ],
  },
  {
    id: "ai-infrastructure-sovereignty",
    title: "Internal AI Infrastructure & Data Sovereignty",
    shortTitle: "Infrastructure & Sovereignty",
    concepts: [
      "infrastructure",
      "data sovereignty",
      "sovereignty",
      "cambrian explosion",
      "tool sprawl",
      "consolidated platform",
      "data lake",
      "clara",
      "clara data",
      "file infrastructure",
      "technology costs",
      "cost control",
      "vendor",
      "platform",
      "integration",
      "shadow it",
      "enterprise ai",
      "private cloud",
      "on-prem",
      "on prem",
      "governance of tools",
      "tooling",
      "stack",
    ],
  },
  {
    id: "leadership-sensemaking",
    title: "Leadership & Sensemaking in the AI Era",
    shortTitle: "Leadership & Sensemaking",
    concepts: [
      "leadership",
      "sensemaking",
      "sense-making",
      "cynefin",
      "nervous-system",
      "nervous system",
      "regulation",
      "mind traps",
      "mind trap",
      "slow down while moving fast",
      "container",
      "organizational fear",
      "hold fear",
      "holding space",
      "framework",
      "adaptive leadership",
      "complex",
      "complexity",
      "uncertainty",
      "pace",
      "calm",
    ],
  },
  {
    id: "future-of-coaching",
    title: "The Future of Coaching & Coaching Bots",
    shortTitle: "Future of Coaching",
    concepts: [
      "coaching bot",
      "coaching bots",
      "ai coach",
      "ai coaching",
      "human coaching",
      "luxury market",
      "weird luxury",
      "premium offering",
      "mid-level",
      "mid level",
      "coach",
      "coaching",
      "facilitation bot",
      "replacement of coaches",
      "human touch",
      "tiered",
      "access to coaching",
    ],
  },
  {
    id: "ai-support-cl",
    title: "How AI might support CL",
    shortTitle: "AI Supporting CL",
    concepts: [
      "ai petal",
      "cultivating leadership",
      "cl strategy",
      "transformation strategy",
      "practical opportunity",
      "concrete opportunity",
      "support cl",
      "our practice",
      "our clients",
      "camp clai",
      "clara",
      "harvest",
      "commons",
      "synthesis",
      "client work",
      "internal capability",
      "pilot",
      "experiment for cl",
      "opportunity for us",
    ],
  },
  {
    id: "risks-fears-growth",
    title: "Risks and Fears and how they may be addressed",
    shortTitle: "Risks, Fears & Growth",
    concepts: [
      "risk",
      "risks",
      "fear",
      "fears",
      "blind spot",
      "blind spots",
      "grow individually",
      "grow collectively",
      "individual growth",
      "collective growth",
      "how might ai enable",
      "mitigation",
      "guardrail",
      "guardrails",
      "anxiety",
      "threat",
      "opportunity cost",
      "unintended",
      "harm",
      "safety",
      "trust erosion",
    ],
  },
  {
    id: "meta-learning",
    title: "Meta: How did we speak with each other?",
    shortTitle: "Meta",
    concepts: [
      "how we spoke",
      "spoke with each other",
      "weave",
      "weaving",
      "between sessions",
      "learning over time",
      "hard to talk",
      "hard for us to talk",
      "meta",
      "process note",
      "dialogue quality",
      "listening",
      "cross-pollination",
      "cross pollination",
      "patterns of conversation",
      "what we avoided",
      "silence",
      "facilitation",
      "how we learn",
      "reflective practice",
      "group dynamics",
      "balcony",
    ],
  },
];

/** Preliminary relational edges for the interactive theme map. */
export const THEME_EDGES = [
  { from: "organizational-overwhelm", to: "workslop-economy" },
  { from: "workslop-economy", to: "expertise-paradox" },
  { from: "expertise-paradox", to: "future-of-coaching" },
  { from: "workplace-grief", to: "leadership-sensemaking" },
  { from: "organizational-overwhelm", to: "workplace-grief" },
  { from: "leadership-sensemaking", to: "ai-principles-humanist" },
  { from: "ai-principles-humanist", to: "ai-support-cl" },
  { from: "ai-infrastructure-sovereignty", to: "ai-support-cl" },
  { from: "ai-support-cl", to: "risks-fears-growth" },
  { from: "meta-learning", to: "organizational-overwhelm", dashed: true },
  { from: "meta-learning", to: "ai-principles-humanist", dashed: true },
  { from: "meta-learning", to: "leadership-sensemaking", dashed: true },
];
